// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsSiteAPI;

namespace NewsSiteAPI.Migrations
{
    [DbContext(typeof(NewsSiteContext))]
    [Migration("20200125152700_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("NewsSiteAPI.Models.RssFeed", b =>
                {
                    b.Property<int>("RssFeedId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Uri")
                        .IsRequired();

                    b.HasKey("RssFeedId");

                    b.ToTable("RssFeed");
                });
#pragma warning restore 612, 618
        }
    }
}
